### ISSUE TITLE
Multiple AutoCompare configurations in same application

### ISSUE THREAD

**Issue by fubar-coder** [StevenGilligan/AutoCompare#11]
It'd be nice to have multiple AutoCompare configurations in the same applications, because sometimes comparisons of objects of the same type might slightly differ.

**Comment by StevenGilligan** [comment]
This was already requested and fixed in issue #6 - Adding support for IoC with an engine

It's in the readme in the list of features but I guess I'll also add a proper code example in there for creating multiple Engines.

For now, look at the tests solution for a code example under `IoCTests.Two_Engines_Can_Run_At_The_Same_Time()`
