### ISSUE TITLE
Alike existing stateprinter

### ISSUE THREAD

**Issue by kbilsted** [StevenGilligan/AutoCompare#4]
Hi Steven

It is with great interest I read about your project as it is very similar to my project state printer https://github.com/kbilsted/StatePrinter

Maybe great stuff can come out of merging the two?

**Comment by StevenGilligan** [comment]
I understand how both libraries use reflection to compile an expression tree, but I can see that they are built to tackle two very different problems. I don't imagine how they could be merged together.  

I much prefer a library to stay lightweight and focusing on doing a single task perfectly, instead of being a jack of all trades that's tackling too many different problems at once.
